### ISSUE TITLE
get code compiling inside beamsim container

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rslinac#1]
At present, it only compiles on Windows with Embarcadero C++ Builder XE7

**Comment by bruhwiler** [comment]
Please reorganize directory structure as you think best.
We should probably use PyTest for testing, so maybe we should emulate in part the standard RS structure for a Python repo
We need to prototype a Sirepo implementation in the next few months, so this should be considered.
Perhaps the closest analog with existing Sirepo implementations is Elegant.

**Comment by bruhwiler** [comment]
Work on Hellweg2D should be charged to the HIPOLIN project.

**Comment by elventear** [comment]
Reviewed the code and it seems to be an [Embarcadero (formerly Borland) C++ Builder](https://www.embarcadero.com/products/cbuilder) GUI application. This means that roughly half of the code is just to layout and define interactions within the GUI, the other half is the backend (a.k.a. Solver) that does the calculations.

C++ Builder provides an API to abstract GUI building and target different platforms. Sadly, Linux/X11 is not one of the supported target platforms and there is no compatible open source that could help porting the code to Linux. This means that to port the application to Linux and provide the same type of functionality via a GUI, it would have to be rebuilt using another Widget framework that supports Linux (Qt, WxWidgets, GDK).

The backend code is a C++ dialect based on some Builder conventions that I think it would be easier to port to straight C++.

In sum, getting the app working on Linux with the exact same functionality with require an non trivial investment of time to get it up and running. My recommendation for a short term target would be to try to extract the backend and make it a standalone command line app.

**Comment by bruhwiler** [comment]
Please separate out the GUI code and don't worry about porting that to
Linux.
We want the kernel to run on Linux.

However, we do want to preserve the ability to clone the code on a Windows
platform and compile it with Embarcadero, including the GUI.

Please organize the code in a sensible way with the GUI code in a separate
directory.
After you have restructured the repo, I'll add in the Windows configuration
files that are used by Embarcadero.

Thanks,
David

**Comment by elventear** [comment]
Working on it.

**Comment by elventear** [comment]
Code compiles and runs on Fedora 23.
