### ISSUE TITLE
Separate GUI code from Physics code

### ISSUE THREAD

**Issue by elventear** [radiasoft/rslinac#10]
Move GUI code into `src/gui` physics code into `src/physics`.

**Comment by elventear** [comment]
@bruhwile I have done the initial reorganization and committed to the `reorg` branch. Could you try to compile it with Embarcadero? 

I had to move all the embarcadero related code to `src/gui` and updated the `hellweg.cbproj` file to use the right paths. Hopefully it works.

**Comment by bruhwiler** [comment]
Verified compilation on Win10 with Embarcadero GUI

**Comment by elventear** [comment]
Merged `reorg` to `master`.
