### ISSUE TITLE
develop script to convert Hellweg particle files back-and-forth to SDDS format

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rslinac#103]
Perhaps I should start by committing some small example particle files to the repo

**Comment by robnagler** [comment]
Why SDDS over HDF5?

**Comment by bruhwiler** [comment]
It's a request from an active Hellweg user, who wants to integrate Hellweg with their other workflows, which include elegant/SDDS and SDDS plotting utilities.

**Comment by bruhwiler** [comment]
@garsuga -- when you will be available to start working on this issue?

**Comment by robnagler** [comment]
I think we are waiting on the particle file examples (both sides). This will be simpler than having @garsuga figure out what those are.

**Comment by bruhwiler** [comment]
We really don't want a script to address this user-requested feature.
I'll create a new, more accurate issue.
