### ISSUE TITLE
modify the equations of motion to use gamma as a dynamical variable

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rslinac#108]
- [x] go to the published equations, and integrate over gamma prior to the conversion from gamma to beta
- [ ] implement in the source code
- [ ] test

**Comment by skutsaev** [comment]
This should be  merged with issue #45, but I don’t know how to do this

**Comment by skutsaev** [comment]
Should be merged with #125

**Comment by bruhwiler** [comment]
Duplicate. Closing.
