### ISSUE TITLE
20221005 Add filename functions or AnsiString support functions

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rslinac#110]
![image](https://user-images.githubusercontent.com/3825435/193705030-625e182b-0d41-4880-9b46-58b448168f57.png)

**Comment by bruhwiler** [comment]
I'm guessing this was caused by merging Sergey's recent updates.
I will make an effort to fix the problem.

**Comment by bruhwiler** [comment]
Yes, this was my fault. @robnagler -- it would be helpful if you could work with me on this to help me understand, so I don't do this again.

**Comment by robnagler** [comment]
I'll take a look.

**Comment by robnagler** [comment]
Need to create methods that do this:

```cpp
static AnsiString GetFileName(AnsiString &F)   //Gets the file name from path
{
  return F.SubString(F.LastDelimiter("/\\")+1,F.Length());
}
//---------------------------------------------------------------------------
static AnsiString GetFileCaption(AnsiString &F)   //Gets the file name without extension
{
  return F.SubString(0,F.LastDelimiter("/.")-1);
}
```

Substring and LastDelimiter are not in our mock AnsiString.cpp so need to either create them or create these file manipulation functions.

**Comment by garsuga** [comment]
@bruhwiler are Sergey's newest changes available on some branch?

**Comment by bruhwiler** [comment]
Yes. The easiest way to see the changes (I think) is too look at file differences from the recently closed (and subsequently reverted) PR, https://github.com/radiasoft/rslinac/pull/109/files

**Comment by robnagler** [comment]
kutsaev_2021b

**Comment by garsuga** [comment]
Opened https://github.com/radiasoft/rslinac/pull/116 to merge changes into kutsaev_2021b
