### ISSUE TITLE
Compilation fails in branch kutsaev_2021b

### ISSUE THREAD

**Issue by ilyapogorelov** [radiasoft/rslinac#118]
The build fails with these error messages along the way:

src/physics/Functions.h: In function ‘AnsiString GetFileName(AnsiString&)’:
src/physics/Functions.h:415:11: error: ‘class AnsiString’ has no member named ‘SubString’
  415 |  return F.SubString(F.LastDelimiter("/\\")+1,F.Length());
      |           ^~~~~~~~~
src/physics/Functions.h:415:23: error: ‘class AnsiString’ has no member named ‘LastDelimiter’
  415 |  return F.SubString(F.LastDelimiter("/\\")+1,F.Length());
      |                       ^~~~~~~~~~~~~
src/physics/Functions.h: In function ‘AnsiString GetFileCaption(AnsiString&)’:
src/physics/Functions.h:420:11: error: ‘class AnsiString’ has no member named ‘SubString’
  420 |  return F.SubString(0,F.LastDelimiter("/.")-1);
      |           ^~~~~~~~~
src/physics/Functions.h:420:25: error: ‘class AnsiString’ has no member named ‘LastDelimiter’
  420 |  return F.SubString(0,F.LastDelimiter("/.")-1);
      |                         ^~~~~~~~~~~~~
[...]
src/physics/BeamSolver.cpp: In member function ‘TResult TBeamSolver::Output(AnsiString&)’:
src/physics/BeamSolver.cpp:5496:2: error: ‘Memo’ was not declared in this scope
 5496 |  Memo->Lines->SaveToFile(FileName);
[...]
make: *** [makefile:35: lib/BeamSolver.o] Error 1

**Comment by bruhwiler** [comment]
This problem is being addressed via Issue #110.

**Comment by ilyapogorelov** [comment]
Closing as redundant.
