### ISSUE TITLE
20221017 Remove unnecessary branches

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rslinac#120]
@garsuga after verifying that master has all the changes, please remove your branches

**Comment by garsuga** [comment]
I cannot find the kustaev_2021b commits in #119, can you correct me if those are present? I think [110-new-commits](https://github.com/radiasoft/rslinac/tree/110-new-commits) contains some needed commits and it is still being shown as ahead of master.

**Comment by robnagler** [comment]
We squash merged so the commit history is flattened.
