### ISSUE TITLE
20221017 Rename repo to rshellweg

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rslinac#121]
See https://github.com/radiasoft/sirepo/issues/4940. Does it make sense to align rslinac to be hellweg? I don't think there will be anything else in this repo.

**Comment by bruhwiler** [comment]
I discussed this with SK and we do not have strong feelings about it. You can proceed as you think best.

**Comment by robnagler** [comment]
hellweg is available on pypi.org, which would be the only "stopper". We should call it rshellweg, since that's our convention. I think that would be consistent with how we work with the other codes. Agreed?

**Comment by bruhwiler** [comment]
I agree that the repo can be renamed to rshellweg/
For naming the URL of the Sirepo app, I would prefer Sirepo Hellweg, without the rs

**Comment by robnagler** [comment]
Yes, that's our convention.

**Comment by garsuga** [comment]
I do not have the right permissions to rename the repo

**Comment by bruhwiler** [comment]
I did it.

**Comment by robnagler** [comment]
NO!

**Comment by robnagler** [comment]
First step is to rename the files and references in the repo, and then rename the repo.

`#define RSLINAC` would now become `#define RSHELLWEG_LINUX`, for example.

**Comment by robnagler** [comment]
I changed it back.
