### ISSUE TITLE
add export-to-SDDS as an option for the SAVE keyword

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rslinac#128]
@bruhwiler will provide some additional context and the reassign this issue to Rob and Garret.

**Comment by bruhwiler** [comment]
- [ ] provide an example output in PIT format @bruhwiler 
 - [ ] write a Python script to convert from PIT format to an SDDS (aka elegant) particle file @garsuga 
 - [ ] based on logic in Python script, edit the Hellweg source code  @skutsaev

**Comment by garsuga** [comment]
What is the status on this?

**Comment by bruhwiler** [comment]
This effort was not completed. Closing issue because funding is no longer available.
