### ISSUE TITLE
How do I install rshellweg on Windows

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rslinac#153]
Are there instructions somewhere for how to install on Windows? A search for "install" in the project didn't yield anything.

I installed the embarcadero compiler, free trial of RAD Studio, and boost through the Rad Studio GetIt package manager.

Then I tried this via git-bash:
```bash
CC=bcc32x CPPFLAGS='-Ic:\program files (x86)\embarcadero\studio\22.0\include\boost_1_70\' pip install .
```

I get the following error:
```
src\libHellweg2D\IniFiles.hpp(4): fatal error C1083: Cannot open include file: 'boost/property_tree/ptree.hpp': No such file or directory
```

Looking in `c:\program files (x86)\embarcadero\studio\22.0\include\boost_1_70\` I see the ptree.hpp file.

I then opened [Hellweg.cbproj](https://github.com/radiasoft/rshellweg/blob/master/src/gui/Hellweg.cbproj) inside of RAD Studio. I tried Project > Make Hellweg. I get 51 errors. Many are about `VCLTee.Chart.hpp`.

```
[bcc32 Error] GeometryForm.h(14): E2209 Unable to open include file 'VCLTee.Chart.hpp'
  Full parser context
    MainUnit.cpp(6): #include MainUnit.h
    MainUnit.h(18): #include GeometryForm.h
```

A search online for that error lead me to more boost include information. Ex https://stackoverflow.com/a/31034239 . I verified that I have `$(CG_32_BOOST_ROOT)` in the System Include Path in tools > options > c++ > paths and directories.

Any advice on what's going on?

One concern is that I have a free trial of RAD Studio so maybe not everything is available?

If it is possible to just share an executable of hellweg for windows with me that would be fine. I only want to run hellweg and view the output. I don't need a working development environment.

**Comment by robnagler** [comment]
Don't use the pip install or the make. I think there are embarcadero  project files. You would run the embarcadero gui to do the build.

**Comment by bruhwiler** [comment]
I went through this recently with the Embarcadero GUI and was eventually successful.
You have to configure your Embarcadero installation correctly to include the VCLTee.Chart.hpp and other neccessary utilities.

@e-carlin -- it's probably best if we screen share.

**Comment by e-carlin** [comment]
Thanks

> You have to configure your Embarcadero installation

That fixed it for me. I uninstalled and upon reinstalling I was more careful about the selections I made. I saw a "TeeChart Standard" option and selected it. 

I get an error when I try to run hellweg from the IDE. But, if I run C:\Users\evan\src\radiasoft\rshellweg\src\gui\Win32\Release\Hellweg then I can get the app to appear.
