### ISSUE TITLE
CMake 3.20.0 or higher is required for ImpactX on Sirepo/Jupyter

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rslinac#156]
I would like to compile ImpactX. However, it complains that a newer version of CMake is required:
***
impactx$ cmake -S . -B build -DImpactX_PYTHON=ON
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  CMake 3.20.0 or higher is required.  You are running version 3.17.4

***
Would it be possible to upgrade CMake on Sirepo-Jupyter this week?

**Comment by bruhwiler** [comment]
Alternatively, please provide instructions for doing a yum install of cmake into a local directory.

**Comment by robnagler** [comment]
You can't yum install on Jupyter. Fedora 36 has CMake 3.25.2. We are at the development test stage. I expect we can move to alpha in a week or so. What's the time frame for ImpactX work?

**Comment by robnagler** [comment]
@Benbenbenin0 you could upgrade your VM to Fedora 36. Exit your VM and then in the VM directory (`~/v`), run:

`radia_run vagrant-sirepo-dev update`

Before you do this, make sure you have committed any changes. The `update` makes a copy of the dot files so your environment should be fully setup on the new VM.  We can do this together if you like.

**Comment by bruhwiler** [comment]
I would like to move forward on a faster time scale.
Ben can work on a dev server for now, but we'll want to do some timing studies soon.

Perhaps a workaround would be to execute CMake on a dev server, tar up the files and then upload the tar file to Sirepo/Jupyter

**Comment by bruhwiler** [comment]
Another workaround is that I can work on NERSC.
I'll give that a try.

**Comment by robnagler** [comment]
You could also install cmake locally in `~/jupyter/bin` and `~/jupyter/lib`: https://cmake.org/install/  This is pretty easy.

Yet another option is to execute cmake on the dev VM and then install just the makefiles on jupyter.
