### ISSUE TITLE
run ImpactX with a particle bunch expanding in a drift

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rslinac#157]
This is the example code,
https://github.com/ECP-WarpX/impactx/tree/development/examples/expanding_beam

We cannot move forward until Issue #156 is resolved.
Perhaps this can be done today in a development environment, where one has sudo privileges.

**Comment by Benbenbenin0** [comment]
Installed cmake without sudo from source file as suggested [#156](https://github.com/radiasoft/rshellweg/issues/156), example ran and analyzed successfully.

**Comment by bruhwiler** [comment]
ImpactX can be compiled with different options for how the computation is accelerated.
Details here, https://impactx.readthedocs.io/en/latest/install/cmake.html#build-options

Let's get initial timings with ImpactX_COMPUTE=NOACC and ImpactX_MPI=OFF
Then let's try it with ImpactX_MPI=ON and run at run time specify two processors.

We can then try OpenMP and then run on a GPU.
Ask @robnagler for instructions on getting access to the RadiaSoft GPU server.

**Comment by bruhwiler** [comment]
We ran out of resources for this task.
