### ISSUE TITLE
run IMPACTX scaling tests on Perlmutter at NERSC

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rslinac#161]
- [x] create an account
- [x] build AMEReX and IMPACTX on Perlmutter
- [ ] run the tests with 10M particles, with MPI only (up to 128 processors), using 1 GPU, using 2 GPUs, and also with OpenMP
- [ ] compare to results obtained on RadiaSoft server and RadiaSoft GPU

**Comment by bruhwiler** [comment]
@Benbenbenin0 - please document the work that has been completed for this task.

**Comment by Benbenbenin0** [comment]
Work Completed:
- Created NERSC Iris Account and accessed login node.
- Installed/built AMEReX and IMPACTX on Perlmutter.
- Ran 'Expanding Particle Bunch in Drift' experiment with 10M particles on 1, 2 GPUs.
- Ran multiple sets of the experiment with MPI, received unusable results.

**Comment by ax3l** [comment]
Hi @Benbenbenin0, I just saw this issue. Can you elaborate on `Ran multiple sets of the experiment with MPI, received unusable results.`?

**Comment by bruhwiler** [comment]
@ax3l -- thanks for the input.

This was some time ago and the project has ended. If I remember correctly, the issue was primarily that the initial tests were done on a shared computing system, and perhaps also there were not enough macroparticles to justify the runs with many processors.

We did sort out the issue satisfactorily.
