### ISSUE TITLE
Merge momentum equations into the code

### ISSUE THREAD

**Issue by skutsaev** [radiasoft/rslinac#164]
I will manually add Ilya's changes line by line, so that both models are kept and can be switched at will

**Comment by bruhwiler** [comment]
I think it would be much better to merge the pull request.

Having both implementations side by side will make the code very messy and difficult to maintain.

Let's make a commitment to the new implementation.

The original implementation will still be available and accessible via GitHub.

**Comment by skutsaev** [comment]
I'll try to make it clean. Making such a global change without the possibility for a user to use an older version may require from us a commitment to fix the code promptly and frequently in case of bugs.
