### ISSUE TITLE
How to use Hellweg to calculate instances

### ISSUE THREAD

**Issue by wanhanlin** [radiasoft/rslinac#173]
Due to being in the early stages of accelerator learning,I am not very familiar with using this software.
How can I install and use Hellweg properly?

**Comment by robnagler** [comment]
It's available on sirepo.com/jupyter, which is a Jupyter notebook environment. 

You can also pip install locally in a Linux environment:

`pip install git+https://github.com/radiasoft/rshellweg.git`

**Comment by wanhanlin** [comment]
Thank you for your answer,but I mean that I did not find the application after downloading the compressed package,do I need to download C++ before I can use it?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "radiasoft/rshellweg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月8日(星期五) 凌晨1:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [radiasoft/rshellweg] How to use Hellweg to calculate instances (Issue #173)





 
It's available on sirepo.com/jupyter, which is a Jupyter notebook environment.
 
You can also pip install locally in a Linux environment:
 
pip install git+https://github.com/radiasoft/rshellweg.git

**Comment by robnagler** [comment]
We do not cut releases. You need to install per the instructions above. This will compile the C++ and link it to the Python.
