### ISSUE TITLE
If BeamType is RANDOM CreateBeam will always fail

### ISSUE THREAD

**Issue by elventear** [radiasoft/rslinac#19]
The following code [(original):](https://github.com/radiasoft/hellweg2d/blob/9c4f7e3c2841f97ae19d4eb4905a0b5f80f991d0/src/physics/BeamSolver.cpp#L1460)

```
bool CST_success=0;
...
  if (BeamType==RANDOM) {
        Beam[0]->MakeGaussEmittance(AlphaCS,BettaCS,EmittanceCS);
    }
    else {
        CST_success=Beam[0]->ReadCSTEmittance(BeamType);
    }
...
    if (!CST_success) {
        return ERR_CURRENT;
    }
```

Seems will always fail when `BeamType` is set to `RANDOM`.

**Comment by elventear** [comment]
@skutsaev as part of my porting efforts, I am trying to run the `default` example. The code that executes everything is very simple and gets triggered by calling `lib_hellweg_run_beam_solver`, for the source see: 

https://github.com/radiasoft/hellweg2d/blob/libHellweg/src/libHellweg2D/libHellweg2D.cpp

Given the input files in the example, I am running into the issue above. I don't know if this situation shouldn't arise but by reading the code it seems non-sensical. I would appreciate if you could shed any light on the issue. 

Maybe I am using the wrong input files?

**Comment by skutsaev** [comment]
Hi, Pepe. This is definitely a bug. The code should be modified as following:
if (BeamType!=RANDOM && !CST_success) return ERR_CURRENT;

The problem with this part is that was added much later to the main code as a hot-patch. For example, the cases when BeamType is CST_Y, or CST_R were abandoned. So, the methods TBeamSolver::CreateBeam() and TBeam::ReadCSTEmittance(TBeamType bType) should be groomed sometimes in the future. First, we need to understand how we will deal with cylindrical coordinates.

**Comment by elventear** [comment]
Sergey, is there an example that you could suggest with the existing code that should work? I want to double check that my changes work on Linux.
