### ISSUE TITLE
hellweg crash under Linux

### ISSUE THREAD

**Issue by elventear** [radiasoft/rslinac#29]
Does not fail with clang, under OS X.

```
[vagrant@localhost rslinac]$ gdb --args python -c 'import rslinac; rslinac.run_beam_solver("tests/run_beam_solver/test_files/rslinac.ini", "tests/run_beam_solver/test_files/input.txt", "output.txt")'
GNU gdb (GDB) Fedora 7.10.1-31.fc23
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...Reading symbols from /usr/lib/debug/usr/bin/python2.7.debug...done.
done.
(gdb) continue
The program is not being run.
(gdb) run
Starting program: /usr/bin/python -c import\ rslinac\;\ rslinac.run_beam_solver\(\"tests/run_beam_solver/test_files/rslinac.ini\",\ \"tests/run_beam_solver/test_files/input.txt\",\ \"output.txt\"\)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff66d1407 in TBeamSolver::GetDimensions (this=this@entry=0x7fffffffd370, Cell=...) at src/physics/BeamSolver.cpp:441
441                     case 90:    Xo[j]=AR[j]; Yo[j]=A12[i][j]; break;
Missing separate debuginfos, use: dnf debuginfo-install libgcc-5.3.1-6.fc23.x86_64 libstdc++-5.3.1-6.fc23.x86_64
```

**Comment by elventear** [comment]
@skutsaev 

In [`TBeamSolver::GetDimensions`](https://github.com/radiasoft/rslinac/blob/d75214170b52c1b772c42a45f482e25079d2ed5a/src/physics/BeamSolver.cpp#L375) I seem to have tracked an issue and I need some guidance for the proper fix.

For `Mode` equal 90; array `AB` is [accessed](https://github.com/radiasoft/rslinac/blob/d75214170b52c1b772c42a45f482e25079d2ed5a/src/physics/BeamSolver.cpp#L500) in the following fashion:

``` c++
for (int i=0;i<Nab;i++) {
...
    switch (Mode) {
        case 90:
             Xi[i]=AB[i];
             break;
...
}
```

where `Nab` is defined [previously](https://github.com/radiasoft/rslinac/blob/d75214170b52c1b772c42a45f482e25079d2ed5a/src/physics/BeamSolver.cpp#L387) as:

``` c++
    switch (Mode) {
          case 90:    
               Nbp=Nb12; 
                Nep=Ne12;
                Nar=Nb23; 
                Nab=Ne23; 
                break;
```

The problem are the following definitions that come from [`ConstUnit.h`](https://github.com/radiasoft/rslinac/blob/d75214170b52c1b772c42a45f482e25079d2ed5a/src/physics/ConstUnit.h):

``` c++
const int Ne23=7;
const int Nab23=4;
const double AB[Nab23]={0.4,0.6,0.8,1.0};
```

So we are setting `Nab` to `Ne23` (7) and then using that value to iterate over `AB` that only has `Nab23` (4) values. I think this discrepancy is causing the crash on Linux that I had previously reported. From the point of the view of accessing the array, the fix is obvious, but from the point of view of Physics code, I am not sure. Could you shed a light on what is the proper fix for this issue?

**Comment by skutsaev** [comment]
Hi Pepe, 

My first answer would be that Nar=Nar23; Nab=Nab23 for cases of 90 and 120 phase advance, and Nar=Nar43; Nab=Nab23 fro 240 degrees. This should be tested, although. I hope to finish all my urgent stuff today and start working on Hellweg on week-end or Monday.

Sergey

**Comment by elventear** [comment]
@skutsaev, I am going fix things as you have suggested and I will merging my changes soon to the `master` branch. I will let you know when it has been merged.

**Comment by elventear** [comment]
Applied fixes suggested and the code does not crash
