### ISSUE TITLE
New code doesn't compile in Embarcadero

### ISSUE THREAD

**Issue by skutsaev** [radiasoft/rslinac#38]
Hi Pepe,

After the last massive changes, the code doesn't compile in Embarcadero on my computer anymore. First, it complains about std:abs() ambiguity. But even when I change it to abs(), it says that some link error occurred and that's it. I pushed some changes that I verified with the previous version but now I am sure if they are copied correct.

Sergey

**Comment by bruhwiler** [comment]
The merged code is compiling for me on Win10 with Embarcadero C++ Builder
10.1

I've verified that the input files now accept comment lines beginning with !

David

On Mon, Sep 12, 2016 at 12:20 AM, Sergey V Kutsaev <notifications@github.com

**Comment by skutsaev** [comment]
I have this: 
![image](https://cloud.githubusercontent.com/assets/21085751/18445846/57a206b6-78d4-11e6-8337-bbceb61584dc.png)

**Comment by bruhwiler** [comment]
My version of Embarcadero doesn't complain about use of
    std:abs()

I suppose you must have an older version.

The project can pay for you to upgrade your version of the compiler.
That may be more efficient than solving problems like this, which may
continue to arise...

David

**Comment by eidelyur** [comment]
David, I also can't work with last version: it compiled but doesn't work
Yury

**Comment by bruhwiler** [comment]
I tried again with Embarcadero this afternoon and saw very strange results.
Trying to git checkout earlier commits was also producing strange results.

I think it's important to exit from Embarcadero when doing anything with Git on Windows or when using the Github Windows application.

I'm not sure how important this is, but I recommend that the Github Windows desktop application should never be open at the same time with the Embarcadero compiler.

Following this rule, I did a command-line git checkout to the code from just before the merge of the branch into master:

bash-4.3$ git checkout 6ecab6cf4a4b8e2769cbb0573a4cf5cc0e50e7ee
Previous HEAD position was 9748c2d... some config files
HEAD is now at 6ecab6c... replaced BeamSolver.cpp with BeamSolve_tempr.cpp

After this, Hellweg2D was compiling and running in the usual way with the Embarcadero compiler.

**Comment by skutsaev** [comment]
So, we can synchronize and it should work?

**Comment by bruhwiler** [comment]
Not yet. I've almost got it working again.

**Comment by bruhwiler** [comment]
Yury and Sergey -- please try the following:

1) quit the Embarcadero compiler
2) open the Github desktop application
3) synchronize
4) exit the Github desktop application
5) open the Embarcadero compiler
6) try to compile and run the updated Hellweg2D source files.

Thanks,
David

**Comment by skutsaev** [comment]
David,
Works fine with me after changing std::abs(x) with abs(x)

**Comment by eidelyur** [comment]
David, everything works now. Thanks a lot to you and Sergey.

Cheers,

Yury
