### ISSUE TITLE
std::abs() problem

### ISSUE THREAD

**Issue by skutsaev** [radiasoft/rslinac#39]
On my computer, the code compiles only if std::abs() is changed with abs(). I don't really feel that it is a $900 worth problem. So, if it can be solved without upgrading Embarcadero, it would be great! 
![image](https://cloud.githubusercontent.com/assets/21085751/18455395/864a3216-78fe-11e6-84d6-3e8dd0e56bf6.png)

**Comment by elventear** [comment]
See [E2015](http://docwiki.embarcadero.com/RADStudio/Seattle/en/E2015_Ambiguity_between_'function1'_and_'function2'_%28C%2B%2B%29). This is an embarcadero compiler problem, where the compiler is getting confused on what function to choose depending on the type.

A simple way to fix this is to tell the compiler which one to use, e.g. `std::abs((__int64)x)`. The reason it is getting confused is because the `abs` is defined for integer types, but I see in `Matrix.cpp` that we are using it on a float.

**Comment by skutsaev** [comment]
OK. That worked. Thank you. Let's stick with this definition then

**Comment by elventear** [comment]
@skutsaev I've been looking more into this issue, I think we are missing:

``` c++
#include <cmath>
```

Which should declare `abs` for floating point types. Could you see if that works in Embarcadero for you? I don't think casting a float to an int is the best approach.

**Comment by skutsaev** [comment]
Unfortunately, it didn't help.

**Comment by elventear** [comment]
Someone has reported the same [issue](http://stackoverflow.com/questions/20199043/im-including-cmath-but-cant-compile-stdabsdouble). Can you do this:

``` c++
#include <cmath>
#include <cstdlib>
```

**Comment by skutsaev** [comment]
Still no

**Comment by elventear** [comment]
Another option is to define this in a common header somewhere:

``` c++
#if __cplusplus <  201103L 
namespace std {
    static double abs(double v) {
        return v < 0? -v : v;
    }

    static float abs(float v) {
        return v < 0? -v : v;
    }
}
#endif
```

Where it is testing for C++11 support, if it is not available, then it will define abs for floating point in the `std` namespace.

**Comment by elventear** [comment]
I don't know how standards compliant is the version of BorlandC++ that you are using, you can also test for the following `#if __BORLANDC__ == <version>`. Here is a list of the predefined [macros](http://docwiki.embarcadero.com/RADStudio/Seattle/en/Predefined_Macros#C.2B.2B_Compiler_Versions_in_Predefined_Macros).

**Comment by skutsaev** [comment]
OK. I used a simpler solution. Changes abs() with mod() from Types.h

**Comment by elventear** [comment]
Sounds good.
