### ISSUE TITLE
Dump beam parameters

### ISSUE THREAD

**Issue by skutsaev** [radiasoft/rslinac#41]
Requested by VD. Add the possibility to dump beam parameters in the output text file. Probably, the best way is to define a keyword DUMP and put it after the element where you want to save the beam parameters. Something like:
CELLS N X Y Z
DUMP beam_01.txt
CELLS N X Y Z
END;

**Comment by eidelyur** [comment]
I suggest very useful keyword

TRACK N1 N2 filename.dat,

where N1 and N2 are initial and last numbers of particle and filename.dat is output file. I made this in my "playing" with code.

Yu.

**Comment by skutsaev** [comment]
Why define N1 and N2?

**Comment by eidelyur** [comment]
Format of filename.dat is ( columns)

particle  x y z energy

Without N1 and N2 file will be so long for all particles

Yu

**Comment by skutsaev** [comment]
OK. I can leave it as optional parameters

**Comment by skutsaev** [comment]
Added the possibility to dump the beam. Need to put keyword SAVE and the file name at the point of interest.
Ex. CELL <>
SAVE beam1.log
DRIFT <>
SAVE beam2.log

Currently, the following parameters: phase, energy, radius, azimuth and vx are exported for all living particles. Will add the possibility to choose the particle range and the parameter selection later today or tomorrow.

**Comment by skutsaev** [comment]
Added the possibility to dump the limited number of particles. If a number N is defined after the file name, the coed will dump the first N particles. If two numbers N1 N2 are defined, the particles from N1 to N2 will be dumped.
Ex. SAVE beam1.log 500
Ex. SAVE beam2.log 100 200

**Comment by eidelyur** [comment]
Great! Thanks a lot.

Yury

**Comment by skutsaev** [comment]
One more upgrade is coming

**Comment by skutsaev** [comment]
Added flags for data output in SAVE line: LOST, ENERGY, PHASE, RADIUS, AZIMUTH, and VX.
