### ISSUE TITLE
Define meshing for DRIFT

### ISSUE THREAD

**Issue by skutsaev** [radiasoft/rslinac#42]
Need to define meshing policy for a drift. I see two options:
1. Define an additional parameter for DRIFT line with number of mesh points
DRIFT 1.0 1.0 500
2. Define a global keyword MESH that will change the number of mesh point for all elements after it.
MESH 500
DRIFT <>
MESH 50
CELL 120 0.4<>
MESH 20
CELL 120 0.99 <>

**Comment by bruhwiler** [comment]
I prefer option 1)

David

**Comment by skutsaev** [comment]
OK. That's much easier

**Comment by skutsaev** [comment]
Implemented the option 1. Now it is possible to define the number of mesh point inside the drift element by adding the third parameter
