### ISSUE TITLE
Major verification: compare results for space-charge effect with another code

### ISSUE THREAD

**Issue by eidelyur** [radiasoft/rslinac#53]
Compare results for space-charge effect (first approach) with code ASTRA

**Comment by elventear** [comment]
Is this verification going to be implement in code? Can we leverage this for automated tests?

**Comment by eidelyur** [comment]
I think no: old approach (Kutsaev) is implemented to code already and work appropriately. I 'll compare results of Hellweg2D calculations with results from ASTRA code
