### ISSUE TITLE
provide a working executable to Paul

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rslinac#68]
Give a working windows executable to @moellep so he can design a prototype UI for Sirepo

**Comment by bruhwiler** [comment]
Latest version of source code compiled after I changed pow(a,b) by making the first argument a float.

However, the resulting executable cannot parse the example input files.

**Comment by skutsaev** [comment]
Executable is here: https://owncloud.radiasoft.org/index.php/s/0pJXmxjviu9RdXE?path=%2FHellweg2D%2Fexecutable_new 
I can upload the intermediate version of the code with a space charge upgrade too.
