### ISSUE TITLE
linux build error

### ISSUE THREAD

**Issue by matsievskiysv** [radiasoft/rslinac#79]
I tried to install python wrapper with command `sudo python setup.py install`. Installation script fails with following message:

> src/libHellweg2D/IniFiles.hpp:4:41: fatal error: boost/property_tree/ptree.hpp: No such file or directory

**Comment by elventear** [comment]
@seregaxvm you need to build from the `integration` branch and there are some dependencies. Like [boost](http://www.boost.org/). In this case you are missing boost.

**Comment by matsievskiysv** [comment]
Thanks, it worked
