### ISSUE TITLE
Integrate with Python

### ISSUE THREAD

**Issue by elventear** [radiasoft/rslinac#8]
The Physics Kernel needs to be executable from Python for integration with [sirepo](https://github.com/radiasoft/sirepo).

**Comment by elventear** [comment]
@robnagler Any comments suggestions about how this has been done in the past? Right now I am thinking of building the code as a shared library and load it within Python with [CFFI](https://cffi.readthedocs.io/en/latest/)

**Comment by robnagler** [comment]
I would use what's most effective. At first, let's wrap as a binary that
gets execute with input/output files like David said with elegant:

https://github.com/radiasoft/sirepo/blob/master/sirepo/template/elegant.py
https://github.com/radiasoft/sirepo/blob/master/sirepo/pkcli/elegant.py

We can skype about this.

**Comment by elventear** [comment]
Have a basic script to call the Beam solver since, 65e7a4e2d2e27446916fd9bcbe2063ae9f27bb85. It does not crash and does seem to parse inputs, consume CPU cycles and generate an output without crashing. Can't verify if the results are correct.
