### ISSUE TITLE
linux simulation crash

### ISSUE THREAD

**Issue by matsievskiysv** [radiasoft/rslinac#80]
running python script with default values taken from [beta.sirepo.com/hellweg->new_simulation](https://beta.sirepo.com/hellweg#/source/h2WKjPGM?show_item_id=emAIEVcP) crushes the linux version of the program with the following error

> terminate called after throwing an instance of 'std::runtime_error'
  what():  LoadData() failed

Code:

```
from rslinac.solver import BeamSolver

ini_file = """
[NUMERIC]
Number of Mesh Points = 20
Spline Interpolation = 0
Smoothing = 0.95
"""
input_file = """
SOLENOID 1000.0 20.0 0.0
BEAM TWISS4D 0.14 2.0 0.0005 0.28 4.0 0.0015 NORM2D 1.0 0.5 90.0 180.0
CURRENT 0.01 1000
END
"""
with open('input.txt', 'w') as f:
    f.write(input_file)
with open('defaults.ini', 'w') as f:
    f.write(ini_file)
solver = BeamSolver('defaults.ini', 'input.txt')
solver.solve()
solver.save_output('output.txt')
```

**Comment by skutsaev** [comment]
There are no accelerator elements in this input file

**Comment by elventear** [comment]
I will have to look deeper into this. The `integration` branch is not up to date with the `master` branch and can't handle files that use the DOS line termination standard.

**Comment by robnagler** [comment]
@seregaxvm We need a little time. @elventear is on vacation so it will be another week before he can look into this.

**Comment by moellep** [comment]
The sirepo generated code should be changed so a small drift gets added if there are no accelerator elements in the simulation.

**Comment by robnagler** [comment]
@garsuga please see if this is still an error.
