### ISSUE TITLE
announce availability of Hellweg in the cloud

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rslinac#81]
A browser-based GUI is now available for open beta testing of Hellweg in the cloud:
https://beta.sirepo.com/hellweg

Improve the repository documentation, including a link to the beta testing site.
Add a reference to Sirepo/Hellweg on the beta test home page at https://beta.sirepo.com
Add a reference to Sirepo/Hellweg on the USPAS resources page, http://uspas.fnal.gov/materials/materials-downloads.shtml

**Comment by bruhwiler** [comment]
1st item is completed. The repository README has been updated.

**Comment by skutsaev** [comment]
Please, add that Hellweg was initially developed in the RF laboratory of National Research Nuclear University "MEPhI" and put a link: http://rflab.mephi.ru/en/

**Comment by bruhwiler** [comment]
Mods to repo README completed per request.

2nd item is also completed.
