### ISSUE TITLE
Field with beam load always bigger than without

### ISSUE THREAD

**Issue by matsievskiysv** [radiasoft/rslinac#86]
Field strength with beam load seems to be always bigger then without beam loading.

Way to reproduce:
Open [sirepo](https://beta.sirepo.com/hellweg), choose `RF fields` example.
Change `source->main->current` to `0.1`, save changes. Start new simulation. Note that beam gained energy. Open `Field Strength` report. Observe field strength with beam loading being bigger then without beam loading.

**Comment by bruhwiler** [comment]
Thank you for reporting this problem @seregaxvm 

This appears to be a bug in the version of rslinac / Hellweg that was ported to Linux and built with the GNU compiler.  This was a prototype effort for a short-lived project and we do not have the resources to update it.

If you build the latest version of Hellweg from it's native GitHub repository,
   https://github.com/radiasoft/rslinac
and compile it on Windows with Embarcadero's C++ Builder, then you will see correct behavior.

I will leave this issue open until the g++/Linux version has been fixed.

**Comment by matsievskiysv** [comment]
> version of rslinac / Hellweg that was ported to Linux and built with the GNU compiler

Is this version publicly available?

**Comment by robnagler** [comment]
Yes, at this branch: https://github.com/radiasoft/rslinac/tree/beamsim_build

**Comment by bruhwiler** [comment]
This version of Sirepo/Hellweg has been retired.
