### ISSUE TITLE
GNU version memory leak

### ISSUE THREAD

**Issue by matsievskiysv** [radiasoft/rslinac#87]
This is a followup to the https://github.com/radiasoft/sirepo/issues/1692.

For the testing purposes rslinac was patched with [debug.patch](https://github.com/radiasoft/rslinac/files/3243635/debug.patch.txt). Following input file was used:

```python
from rslinac import solver
import gc

ini_file = """
[NUMERIC]
Number of Mesh Points = 50
Spline Interpolation = 0
Smoothing = 0.95
"""

with open('defaults.ini', 'w') as f:
    f.write(ini_file)

input_file = """
BEAM SPH2D 0.001 0 0.0 NORM2D 0.025 1e-05 90.0 180.0
CURRENT 0.1 1000
POWER 1.0 2856.0 0.0
CELLS 2 120.0 0.3 50.0 0.0 0.1
END
"""

with open('input.txt', 'w') as f:
    f.write(input_file)

s = solver.BeamSolver('defaults.ini', 'input.txt')
s.solve()
s.save_output('output.txt')

del s
gc.collect()
```

After the `s` deletion and garbage collection cycle, solution data is still present in memory.
Seems that the destructor does not run for the [`PyHellwegBeamSolver`](https://github.com/radiasoft/rslinac/blob/master/pyhellweg.pyx#L51-L75) object. Maybe it should be defined explicitly.

Additionally, `valgrind` check was performed.
```bash
export PYTHONMALLOC=malloc
valgrind --leak-check=full \
	 --show-leak-kinds=all \
	 --track-origins=yes \
	 --error-limit=no \
	 --suppressions=valgrind.sup \
	 --log-file=valgrind.log \
	 python3.7 /tmp/rf-fields.py
```
This is the [output](https://github.com/radiasoft/rslinac/files/3243656/valgrind.log) of the valgrind being run with the suppression file [valgrind.sup](https://github.com/radiasoft/rslinac/files/3243655/valgrind.sup.txt).

**Comment by bruhwiler** [comment]
Need to test whether this is still a problem.
It could be related to issue #127

**Comment by skutsaev** [comment]
I checked the code with CodeGuard for multiple examples, including the mentioned one, and fixed several memory leaks
