### ISSUE TITLE
update linux build to work with recent Boost version

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rslinac#88]
It looks like ptree has been moved around or changed in Boost since we last compiled Hellweg on Linux.
The error below occurs in the beamsim_build branch

![image](https://user-images.githubusercontent.com/3825435/176231235-56770d34-7502-4c2a-8810-1549ad23e4f8.png)

**Comment by bruhwiler** [comment]
@garsuga -- what is the status of this issue?

**Comment by garsuga** [comment]
It is almost done, debugging some other build stuff with Rob still.

**Comment by garsuga** [comment]
Closed with https://github.com/radiasoft/download/pull/309

**Comment by bruhwiler** [comment]
I want to be able to manually build rslinac on Sirepo/Jupyter as a developer.
So it seems that there will have to be a fix to *this* repo as well.
