### ISSUE TITLE
Problems with multiple sections 

### ISSUE THREAD

**Issue by skutsaev** [radiasoft/rslinac#92]
1. Multiple section don't work correctly
2. Phase shift is not working correctly.
3. Verify that when simulating the linac with 2 sections with different frequencies, the bunch length doesn't change with the frequency change (i.e. x/lmb1 != x/lmb2 but x/lmb2 = x/lmb1 * lmb2/lmb1)

**Comment by bruhwiler** [comment]
@skutsaev -- if the frequency is the same in two linac sections, is there still a problem?

**Comment by bruhwiler** [comment]
@skutsaev -- please make this your next priority.

**Comment by skutsaev** [comment]
Fixed
