### ISSUE TITLE
install AMReX on Sirepo/Jupyter

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/rslinac#95]
https://github.com/AMReX-Codes/amrex

Build instructions are here,
https://amrex-codes.github.io/amrex/docs_html/BuildingAMReX.html#building-libamrex

I tried the configure --prefix command which seemed to work out of the box on Jupyter

**Comment by garsuga** [comment]
Closed with https://github.com/radiasoft/download/pull/338
