### ISSUE TITLE
Create makefile for rslinac

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rslinac#96]

**Comment by bruhwiler** [comment]
I'll create a simple example to get us started.

**Comment by bruhwiler** [comment]
In my comment above, I was thinking of a Makefile for the upcoming port to use AMReX.  

However, I believe the intent of this issue to create a Makefile for the existing linux build of Hellweg.

I would like this issue to be closed soon, so that effort can be directed to issue #93
