### ISSUE TITLE
BeamSolver retains global state

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rslinac#97]
beam_solver_test.py doesn't pass, because there's global state held in BeamSolver.  The individual cases pass, but something in the library holds state that it shouldn't.

**Comment by robnagler** [comment]
run as separate tests.

**Comment by robnagler** [comment]
This is a different bug.

**Comment by robnagler** [comment]
Workaround 36e11c83875140d453083126a193e06a7c656c96

**Comment by robnagler** [comment]
This is really still a problem if you are using BeamSolver more than once in a program. Generally not what we do in the agent, but still is a bug. If using in a IPython notebook, this could be a problem.

**Comment by bruhwiler** [comment]
This is consistent with my experience from using Hellweg as compiled for windows. You don't execute the solver more than once -- you have to exit the application and restart.

**Comment by bruhwiler** [comment]
Closing here. I'll create a separate issue to address this bug in the future.
