### ISSUE TITLE
20221005 Fix setup.py to create pyhellweg.cpp

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rslinac#99]

**Comment by bruhwiler** [comment]
@robnagler -- when I try 'pip install -e .' or 'pip install .' I get the following compilation error:

**Comment by bruhwiler** [comment]
![image](https://user-images.githubusercontent.com/3825435/193702163-d5105f66-ede5-4f00-a8be-5e8265673cf9.png)

**Comment by bruhwiler** [comment]
I think this is related to pyhellweg.pyd not being present, and I forget the work around.

**Comment by robnagler** [comment]
You need to run make first, I think, because it will create lib/pyhellweg.cpp.
